openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0

servers:
  - url: 'https'
paths:
  /users:
    get:
      summary: Get all users
      tags:
        - User
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                users:
                  - id: 1
                    username: user123
                    email: user123@example.com
                  - id: 2
                    username: anotheruser
                    email: anotheruser@example.com

    post:
      summary: Create a new user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            example:
              username: newuser
              email: newuser@example.com
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              example:
                id: 3
                username: newuser
                email: newuser@example.com

  /users/{userId}:

    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
        description: ID of the user

    get:
      summary: Get user by ID
      tags:
        - User
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                username: user123
                email: user123@example.com

    put:
      summary: Update user by ID
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            example:
              username: updateduser
              email: updateduser@example.com
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              example:
                id: 1
                username: updatedUser
                email: updateduser@example.com

    delete:
      summary: Delete user by ID
      tags:
        - User
      responses:
        '204':
          description: User deleted successfully
  /accounts:
    get:
      summary: Get all accounts
      tags:
        - Accounts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                accounts:
                  - id: 101
                    balance: 100.00
                  - id: 102
                    balance: 50.00

    post:
      summary: Create a new account
      tags:
        - Accounts
      requestBody:
        required: true
        content:
          application/json:
            example:
              balance: 50.00
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              example:
                id: 103
                balance: 50.00

  /accounts/{accountId}:
    parameters:
      - name: accountId
        in: path
        required: true
        schema:
          type: integer
        description: ID of the account

    get:
      summary: Get account by ID
      tags:
        - Accounts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: 101
                balance: 100.00

    put:
      summary: Update account by ID
      tags:
        - Accounts
      requestBody:
        required: true
        content:
          application/json:
            example:
              balance: 75.00
      responses:
        '200':
          description: Account updated successfully
          content:
            application/json:
              example:
                id: 101
                balance: 75.00

    delete:
      summary: Delete account by ID
      tags:
        - Accounts
      responses:
        '204':
            description: Account deleted successfully

